# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: assets.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='assets.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x61ssets.proto\"\x98\x01\n\x0b\x43reateAsset\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x11\n\tfile_name\x18\x03 \x01(\t\x12\x11\n\tfile_hash\x18\x04 \x01(\t\x12\x18\n\x10\x63hild_public_key\x18\x05 \x01(\t\x12\x17\n\x0f\x63hild_key_index\x18\x06 \x01(\r\x12\x16\n\x0eis_empty_asset\x18\x07 \x01(\x08\x62\x06proto3')
)




_CREATEASSET = _descriptor.Descriptor(
  name='CreateAsset',
  full_name='CreateAsset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='CreateAsset.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='CreateAsset.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='CreateAsset.file_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_hash', full_name='CreateAsset.file_hash', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='child_public_key', full_name='CreateAsset.child_public_key', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='child_key_index', full_name='CreateAsset.child_key_index', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_empty_asset', full_name='CreateAsset.is_empty_asset', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=169,
)

DESCRIPTOR.message_types_by_name['CreateAsset'] = _CREATEASSET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateAsset = _reflection.GeneratedProtocolMessageType('CreateAsset', (_message.Message,), dict(
  DESCRIPTOR = _CREATEASSET,
  __module__ = 'assets_pb2'
  # @@protoc_insertion_point(class_scope:CreateAsset)
  ))
_sym_db.RegisterMessage(CreateAsset)


# @@protoc_insertion_point(module_scope)
